name: Build ChatGPT Bundle

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: pip install pyyaml

      - name: Make bundle from manifest
        run: |
          python - << 'PY'
          import yaml, os, sys, pathlib
          manifest_path = "src/empfaenger/READTHIS_FOR_CHATGPT.yml"
          out_path = "CHATGPT_BUNDLE.txt"
          if not os.path.exists(manifest_path):
            print("Manifest not found", file=sys.stderr); sys.exit(1)
          with open(manifest_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
          watch = data.get("watch", [])
          lines = []
          for rel in watch:
            p = pathlib.Path(rel)
            if not p.exists():
              lines.append(f"\n===== {rel} (MISSING) =====\n")
              continue
            lines.append(f"\n===== BEGIN {rel} =====\n")
            with open(p, "r", encoding="utf-8", errors="ignore") as src:
              lines.append(src.read())
            lines.append(f"\n===== END {rel} =====\n")
          with open(out_path, "w", encoding="utf-8") as out:
            out.write("".join(lines))
          print(f"Wrote {out_path} with {len(watch)} files.")
          PY

      - name: Commit bundle
        run: |
          git config user.name "repo-bot"
          git config user.email "repo-bot@users.noreply.github.com"
          git add CHATGPT_BUNDLE.txt
          git commit -m "chore: update CHATGPT_BUNDLE from manifest" || echo "No changes"
          git push
